
#task: detect # (str) 
mode: train # (str) 

# Train settings -------------------------------------------------------------------------------------------------------
model: yolov3 # (str, optional) path to model file, 
name:  #
data: cifar10 # (str, optional) path to data file, 
in_chans: 3 #(int) dimension of input
imgsz: 416 # (int) input images size as int for train and val modes
S: [13, 26, 52]
iou_thresh: 0.5
nms_thresh: 0.45

# Config data ------------------------------------------------------------------------------------------------------
root: ./yodata
data_file: ./yodata/data.yaml
# train_path: ./train 
# val_path: ./val
# test_path: ./test
nc: 80
names: car 

# Hyperparameter---------------------------------------------------------------------------------------------------------------------------
epochs: 10 # (int) number of epochs to train for
batch: 16 # (int) number of images per batch 
dtype: bf16 # [None, bf16]
devices: cuda # (int ) device to run on, i.e. cuda  or device=cpu
#pretrained: None # (bool | str) whether to use a pretrained model (bool) or a model to load weights from (str)
optimizer: Adam # (str) optimizer to use, choices=[Adam, AdamW, None]
weight_decay: 0.05
lr: 0.001
beta1: 0.9
beta2: 0.999
eps: 1e-8
num_workers: 1

# output
save_dir: ./outputs
logger: logging

